### ISSUE TITLE
Comentários

### ISSUE THREAD

**Issue by leopoldomt** [LGR3/if1001-Minimal_Meditation#2]
Senti falta do mockup da aplicação. 

Seria importante manter um registro histórico do uso do app, para ter uma ideia de quanto tempo se passou meditando, podia usar isto inclusive pra gamificar a aplicação. 

Seria interessante considerar incrementar a funcionalidade do app com recursos do dispositivo móvel. Que funcionalidades podem ser melhoradas ou adicionadas que usem recursos do dispositivo, como câmera, sensores, conectividade, localização, etc?

**Comment by LGR3** [comment]
> _Senti falta do mockup da aplicação._
A princípio a ideia é ser um clone from scratch (em Kotlin no Android Studio) do One-Moment Medt.  
Deixá-lo bonito como o original (fotos embedded no Readme).

Implementarei : 
> _Seria importante manter um registro histórico do uso do app, para ter uma ideia de quanto tempo se passou meditando, podia usar isto inclusive pra gamificar a aplicação._

Persistir o número de sessões de meditação e o tempo total de meditação.

**Comment by LGR3** [comment]
> _Senti falta do mockup da aplicação._

A princípio a ideia é ser um clone from scratch (em Kotlin no Android Studio) do One-Moment Medt.
Deixá-lo bonito como o original (fotos embedded no Readme).

Implementarei :

> _Seria importante manter um registro histórico do uso do app, para ter uma ideia de quanto tempo se passou meditando, podia usar isto inclusive pra gamificar a aplicação._

Persistir o número de sessões de meditação e o tempo total de meditação.
